sudo: required

env:
  - VERSION=0.9

services:
  - docker

before_install:
  - sudo apt-get -y purge docker-engine
  - bash <(curl -fsSL https://get.docker.com/)
  - docker version
  - docker network create --driver=bridge --subnet=192.168.0.0/16 --opt="com.docker.network.driver.mtu=1450" --opt="com.docker.network.bridge.name=redd0" nanobox
  - sudo apt-get -y install python-pip
  - sudo pip install docker==2.7.0 docker-squash
  - git clone https://github.com/nanobox-io/nanobox-hooks-unfs.git hooks
  - docker build -t nanobox/unfs:$VERSION ./$VERSION

script:
  - sudo stdbuf -oL test/run_all.sh $VERSION
  - sudo stdbuf -oL hooks/test/run_all.sh ${VERSION}

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - "echo \"Branch: '$BRANCH'; Version: '$VERSION'\";"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/unfs ./${VERSION};
  - docker-squash -t ${NAMESPACE}/unfs:squashed -f nanobox/runit --tmp-dir /var/tmp/squasher ${NAMESPACE}/unfs
  # `$VERSION-beta` tag is always pushed (master or any dev branch)
  - docker tag ${NAMESPACE}/unfs:squashed ${NAMESPACE}/unfs:${VERSION}-beta;
  - docker push ${REMOTE}${NAMESPACE}/unfs:${VERSION}-beta;
  # `beta` tag is always pushed (master or any dev branch)
  - if [ "$VERSION" == "0.9" ]; then
    docker tag ${NAMESPACE}/unfs:squashed ${NAMESPACE}/unfs:beta;
    docker push ${REMOTE}${NAMESPACE}/unfs:beta;
    fi
  # `latest` tag is only pushed on master && most recent version
  - if [ "$BRANCH" == "master" ] && [ "$VERSION" == "0.9" ]; then
    docker tag ${NAMESPACE}/unfs:squashed ${NAMESPACE}/unfs;
    docker push ${REMOTE}${NAMESPACE}/unfs;
    fi
  # `$VERSION` (latest/stable implied) tag is only pushed on master. tag branch for clarity otherwise (`$VERSION-$BRANCH`)
  - if [ "$BRANCH" == "master" ]; then
    docker tag ${NAMESPACE}/unfs:squashed ${NAMESPACE}/unfs:${VERSION};
    docker push ${REMOTE}${NAMESPACE}/unfs:${VERSION};
    else
    docker tag ${NAMESPACE}/unfs:squashed ${NAMESPACE}/unfs:${VERSION}-${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/unfs:${VERSION}-${BRANCH//\//_};
    fi
